### ISSUE TITLE
edged shapes vs. official k8s logo (round shapes)

### ISSUE THREAD

**Issue by cy4n** [octo-technology/kubernetes-icons#5]
hi, (first of all, awesome icons,  thanks for sharing)
this is more of a feature request than an "issue".

while using the official icons and icons from this repo in the same presentation, i realized that the official logo has rounded corners ( https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png ), while this repo's have edged corners. 
would love if there was a matching version
cheers, 
chris

**Comment by etiennecoutaud** [comment]
Hi @cy4n 

You are completely right about rounded corners. We are already working on this in https://github.com/kubernetes/community/pull/2192 😃

**Comment by cy4n** [comment]
awesome

**Comment by cy4n** [comment]
dammit. guess someone has to update their presentation for this weeks talk. ;)
