### ISSUE TITLE
Cloud provider and external ip

### ISSUE THREAD

**Issue by FredericLeroy** [octo-technology/kubernetes-icons#6]
I am designing a small app, and start with services. I am thinking that it misses external ip
given by the cloud provider. Is it intended ?
One of my service can't be managed by an ingress controller and I don't know how
to represent external access to it.

Thank you for your icons.

Kind regards,

**Comment by arnaudmz** [comment]
AFAIK, External IP are not K8s resources, more kind of attributes of regular services. I'm not sure how we could represent them either.

If you have any suggestion, I'd be glad to draft something.

cheers

**Comment by FredericLeroy** [comment]
I understand it's optional and external. So logically it is not part of kubernetes although it augments k8s.
Maybe we could represent a cloud provider with its own sets of icons, and adding "icons tag" to apply on existing k8S icons. Tags would be simply representing attributes.

**Comment by arnaudmz** [comment]
Could you provide a P/R to https://github.com/kubernetes/community/tree/master/icons, it the official repo now!!
