### ISSUE TITLE
Adding pod"s" icon

### ISSUE THREAD

**Issue by FredericLeroy** [octo-technology/kubernetes-icons#7]
Hello,

I am using endpoints to represent a set of pods in my drawings.
But my team have difficulties to read it because it was too similar to services icon.

So I draw a pods icon upon request.

You can see it in my fork: https://github.com/FredericLeroy/kubernetes-icons/blob/feature/add-pods/png/k8s_resources/labeled/pods.png

Are you interested to have it ?

Cheers,

**Comment by arnaudmz** [comment]
Sure, why not.
Please submit your P/R to https://github.com/kubernetes/community/tree/master/icons
This repo is now obsolete as it's been included into an official K8s repo!!
